inherit_from: .rubocop_todo.yml

require: rubocop-ordered_methods

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/rubocop-ordered_methods.rb
