inherit_from: .rubocop_todo.yml

require: rubocop-ordered_methods

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.4

# Subtle, left to author's discretion. In a long method with many guard clauses,
# a blank line may help. But, in a short method, especially with only a single
# guard clause, a blank line can be disruptive.
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/rubocop-ordered_methods.rb

# Use the semantic style. If a block has side effects use `do`, and if it is
# pure use `{}`. This style is too nuanced for a linter, so the cop is
# disabled.
Style/BlockDelimiters:
  Enabled: false
